version: '3.5'
services:    
    mariadb:
      build:
        context: ./requirements/mariadb
        args:
          MYSQL_DB: ${MYSQL_DB}
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      container_name: mariadb
      image: mariadb
      volumes: 
        - db:/var/lib/mysql
      ports:
        - "3306:3306"
      restart: always
      networks: 
       - mynet

    wordpress: 
      build:
        context: ./requirements/wordpress
      container_name: wordpress
      image: wordpress
      depends_on:
        - mariadb 
      volumes:      
        - wp:/var/www/html/wordpress
      env_file: .env  
      restart: always
      networks:
        - mynet
    
    nginx:
      build: ./requirements/nginx
      container_name: nginx
      image: nginx
      ports:
        - "443:443"
      volumes:
        - wp:/var/www/html/wordpress
      restart: always
      networks: 
        - mynet
      depends_on:
        - wordpress
      
networks:
  mynet:
    driver: bridge

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jhizdahr/data/db
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jhizdahr/data/wp
