DROP DATABASE IF EXISTS ${MYSQL_DB};
DROP USER IF EXISTS '${MYSQL_USER}'@'%';
CREATE DATABASE '${MYSQL_DB}';
CREATE USER '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}'
GRANT ALL ON ${MYSQL_DB}.* TO '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}' WITH GRANT OPTION;
FLUSH PRIVILEGES;